default_install_hook_types: ["pre-commit", "commit-msg"]
repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: scripts/mypy.sh
        language: system
        types_or: [python, pyi]
        pass_filenames: false
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: pipenv-requirements
        name: pipenv-requirements
        files: Pipfile\.lock
        language: system
        pass_filenames: false
        entry: sh -c 'pipenv requirements | grep -vF --regex="-i https://pypi.org/simple" >| requirements.txt'
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
